'use strict';Object.defineProperty(exports,'__esModule',{value:true});var _createClass=function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if('value'in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor)}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor}}();var _ErrorBadRequest=require('./ErrorBadRequest');var _ErrorBadRequest2=_interopRequireDefault(_ErrorBadRequest);function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{default:obj}}function _asyncToGenerator(fn){return function(){var gen=fn.apply(this,arguments);return new Promise(function(resolve,reject){function step(key,arg){try{var info=gen[key](arg);var value=info.value}catch(error){reject(error);return}if(info.done){resolve(value)}else{return Promise.resolve(value).then(function(value){step('next',value)},function(err){step('throw',err)})}}return step('next')})}}function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError('Cannot call a class as a function')}}/**
 * Class represents bot that adds post on wall
 * @param {String} token - access token
 */var VkPostBot=function(){function VkPostBot(token){_classCallCheck(this,VkPostBot);this.token=token}/**
   * Add post on community wall
   * @param params {Object} - Parameters of post
   * @param params.ownerId - (Required) community ID - negative value
   * @param params.friendsOnly - 1 — post will be available to friends only, 0 — post will be available to all users (default)
   * @param params.fromGroup - 1 — post will be published by the community, 0 — post will be published by the user (default)
   * @param params.message - (Required if attachments is not set.) Text of the post.
   * @param params.attachments - (Required if message is not set.) List of objects attached to the post
   */_createClass(VkPostBot,[{key:'post',value:function(){var _ref=_asyncToGenerator(/*#__PURE__*/regeneratorRuntime.mark(function _callee(params){var result,friendsOnly,fromGroup,json;return regeneratorRuntime.wrap(function _callee$(_context){while(1){switch(_context.prev=_context.next){case 0:result=void 0;friendsOnly=params.friendsOnly||0;fromGroup=params.fromGroup||0;if(params.message){_context.next=13;break}if(!params.attachments){_context.next=10;break}_context.next=7;return fetch('https://api.vk.com/method/wall.post?owner_id='+params.ownerId+'&friends_only='+friendsOnly+'&from_group='+fromGroup+'&access_token='+this.token+'&v=5.71&attachments='+params.attachments);case 7:result=_context.sent;_context.next=11;break;case 10:throw new _ErrorBadRequest2.default('One of the parameters specified was missing or invalid: invalid message param');case 11:_context.next=22;break;case 13:if(!params.attachments){_context.next=19;break}_context.next=16;return fetch('https://api.vk.com/method/wall.post?owner_id='+params.ownerId+'&friends_only='+friendsOnly+'&from_group='+fromGroup+'&message='+params.message+'&access_token='+this.token+'&v=5.71&attachments='+params.attachments);case 16:result=_context.sent;_context.next=22;break;case 19:_context.next=21;return fetch('https://api.vk.com/method/wall.post?owner_id='+params.ownerId+'&friends_only='+friendsOnly+'&from_group='+fromGroup+'&message='+params.message+'&access_token='+this.token+'&v=5.71');case 21:result=_context.sent;case 22:_context.next=24;return result.json();case 24:json=_context.sent;if(!json.hasOwnProperty('response')){_context.next=27;break}return _context.abrupt('return',json.response);case 27:throw new _ErrorBadRequest2.default(json.error.error_msg);case 28:case'end':return _context.stop();}}},_callee,this)}));function post(_x){return _ref.apply(this,arguments)}return post}()}]);return VkPostBot}();exports.default=VkPostBot;